@url = http://localhost:8000/api/aksesor

GET {{url}} HTTP/1.1
#######

GET {{url}}/1 HTTP/1.1
####### 

POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "nama":"Norman",
    "instansi":"USN",
    "jk":"Pria",
    "jenis":"Eksternal"

}
#############
     
PUT {{url}}/1 HTTP/1.1
Content-Type: application/json

{
    "nama":"Yosep Kungkung, S.Pd, S.Kom",
    "instansi":"SMK 8 TIK Jayapura",
    "jk":"Pria",
    "jenis":"Internal"

}
#############


   
DELETE  {{url}}/3 HTTP/1.1
Content-Type: application/json
#############