@url = http://localhost:8000/api/paket

GET {{url}} HTTP/1.1
#######

GET {{url}}/15 HTTP/1.1
####### 

POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "kode" : "MP1223",
    "alokasiwaktu" : "1 Jam",
    "bentukpenugasan" : "Perorangan",
    "judultugas" : "dwwsads",
    "jurusan_id" : 1,
    "tahunajaran_id" : 1,
    "aksesorinternal" : 1,
    "aksesoreksternal" : 2,
    "kompetensis":[
      {"elemenkompetensi":"Kompetensi 1"}
    ]
   

}
#############
      
PUT {{url}}/15 HTTP/1.1
Content-Type: application/json

{
  "id": 15,
  "kode": "MP1223",
  "alokasiwaktu": "1 Jam",
  "bentukpenugasan": "Perorangan",
  "judultugas": "dwwsads",
  "jurusan_id": 1,
  "tahunajaran_id": 1,
  "aksesoreksternal": 2,
  "aksesorinternal": 1,
  "created_at": "2024-02-27T03:51:57.000000Z",
  "updated_at": "2024-02-27T03:51:57.000000Z",
  "kompetensis": [
    {
      "id": 2,
      "elemen": "Kompetensi XXXXXX22222",
      "paket_id": 15,
      "created_at": "2024-02-27T03:51:57.000000Z",
      "updated_at": "2024-02-27T04:53:22.000000Z"
    },
    {
      "id": 3,
      "elemen": "Kompetensi 2",
      "paket_id": 15,
      "created_at": "2024-02-27T05:00:01.000000Z",
      "updated_at": "2024-02-27T05:00:01.000000Z"
    }
  ]
}

#############


   
DELETE  {{url}}/3 HTTP/1.1
Content-Type: application/json
#############